export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_FIRSTNAME = 'UPDATE_FIRSTNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_LASTNAME = 'UPDATE_LASTNAME';
export const OPEN_CENTER = 'OPEN_CENTER';
export const CLOSE_CENTER = 'CLOSE_CENTER';
